# -*- coding: utf-8 -*-
"""Emit the EBCDIC cp037 decode table as a TypeScript module.

Node's TextDecoder has no 'ibm037' encoding, so the LOADFILE cannot be decoded
with the platform's own decoder. This writes the 256-entry mapping once, from
Python's codec, rather than hand-typing it.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "cp037.ts")

chars = [bytes([i]).decode("cp037") for i in range(256)]
lines = []
for row in range(16):
    part = "".join("\\u%04x" % ord(chars[row * 16 + col]) for col in range(16))
    lines.append("  '%s' +   // 0x%02X-0x%02X" % (part, row * 16, row * 16 + 15))

body = "\n".join(lines).rstrip(" +")

src = '''/**
 * EBCDIC (IBM code page 037) decode table.
 *
 * The LOADFILE is EBCDIC. Node's TextDecoder does not support 'ibm037' — it
 * throws RangeError — so the mapping is carried here. Generated by
 * scripts/gen_cp037.py from Python's cp037 codec; do not hand-edit.
 */
const CP037 =
%s
  '';

/** Decodes an EBCDIC buffer to a JavaScript string. */
export function decodeCp037(buf: Buffer | Uint8Array): string {
  let out = '';
  for (let i = 0; i < buf.length; i++) out += CP037[buf[i]];
  return out;
}
''' % body

open(OUT, "w", encoding="utf-8").write(src)
print("wrote", os.path.normpath(OUT))
print("sanity: 0xC1 ->", repr(chars[0xC1]), " 0xF0 ->", repr(chars[0xF0]), " 0x40 ->", repr(chars[0x40]))
